version: "3.4"
services:
  mongodb-configsvr-primary:
    image: 'bitnami/mongodb-sharded:5.0.14'
    environment:
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_PORT_NUMBER=27018
      - MONGODB_ROOT_PASSWORD=sBL2y7Uuxqyi
      - MONGODB_ADVERTISED_HOSTNAME=172.17.16.9
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    ports:
      - "27018:27018"
    restart: unless-stopped

  mongos:
    image: 'bitnami/mongodb-sharded:5.0.14'
    environment:
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_ROOT_PASSWORD=sBL2y7Uuxqyi
      - MONGODB_CFG_PRIMARY_HOST=172.17.16.9
      - MONGODB_CFG_PRIMARY_PORT_NUMBER=27018
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_ADVERTISED_HOSTNAME=172.17.16.9
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017:27017"
    network_mode: "host"
    restart: unless-stopped

  mongodb-shard-primary:
    image: 'bitnami/mongodb-sharded:5.0.14'
    environment:
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=0.5
      - MONGODB_PORT_NUMBER=27019
      - MONGODB_ROOT_PASSWORD=sBL2y7Uuxqyi
      - MONGODB_MONGOS_HOST=172.17.16.9
      - MONGODB_ADVERTISED_HOSTNAME=172.17.16.9
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    ports:
      - "27019:27019"
    restart: unless-stopped

  mongodb-shard-secondary:
    image: 'bitnami/mongodb-sharded:5.0.14'
    depends_on:
      - mongodb-shard-primary
    environment:
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=0.5
      - MONGODB_PORT_NUMBER=27020
      - MONGODB_INITIAL_PRIMARY_HOST=172.17.16.9
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27019
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=sBL2y7Uuxqyi
      - MONGODB_ADVERTISED_HOSTNAME=172.17.16.9
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    ports:
      - "27020:27020"
    restart: unless-stopped